import { NextResponse } from 'next/server'
import { z } from 'zod'

const metadataQuerySchema = z.object({
  name: z.string().trim().min(1).max(32).default('CowChain Token'),
  symbol: z.string().trim().min(1).max(10).default('COW'),
  description: z.string().trim().max(200).optional(),
  image: z.string().trim().optional(),
})

function resolveAbsoluteUrl(value: string | undefined, requestUrl: string, fallbackPath: string) {
  const baseUrl = new URL(requestUrl)

  if (!value?.trim()) {
    return new URL(fallbackPath, baseUrl.origin).toString()
  }

  try {
    return new URL(value, baseUrl.origin).toString()
  } catch {
    return new URL(fallbackPath, baseUrl.origin).toString()
  }
}

export async function GET(request: Request) {
  const url = new URL(request.url)
  const parsed = metadataQuerySchema.safeParse({
    name: url.searchParams.get('name') || undefined,
    symbol: url.searchParams.get('symbol') || undefined,
    description: url.searchParams.get('description') || undefined,
    image: url.searchParams.get('image') || undefined,
  })

  if (!parsed.success) {
    return NextResponse.json(
      {
        ok: false,
        error: 'Invalid token metadata query.',
        issues: parsed.error.flatten(),
      },
      { status: 400 }
    )
  }

  const { name, symbol, description, image } = parsed.data
  const imageUrl = resolveAbsoluteUrl(image, request.url, '/milk-token.png')

  return NextResponse.json(
    {
      name,
      symbol,
      description: description || `Official ${name} token metadata generated by MilkChain.`,
      image: imageUrl,
      external_url: url.origin,
    },
    {
      headers: {
        'cache-control': 'public, max-age=300, s-maxage=300',
      },
    }
  )
}
